# Generated by Django 2.0.6 on 2018-06-13 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20180613_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 5, 21, 20, 308775, tzinfo=utc)),
        ),
    ]
